export const GET_USER = "GET_USER";
export const SET_WORKING_BRANCH = "SET_WORKING_BRANCH";
export const GET_USERS = "GET_USERS";
export const GET_USER_ID = "GET_USER_ID";
export const GET_BRANCHES = "GET_BRANCHES";
export const GET_SPECIALTIES = "GET_SPECIALTIES";
export const GET_ROLES = "GET_ROLES";
export const ERROR = "ERROR";
export const DELETE_USER = "DELETE_USER";

export const USER_LOGOUT = "USER_LOGOUT";
export const CLEAR_USERID = "CLEAR_USERID";
export const GET_SERVICES = "GET_SERVICES";
export const GET_CLIENTS = "GET_CLIENTS";
export const GET_CLIENT_ID = "GET_CLIENT_ID";
export const CLEAR_CLIENT_ID = "CLEAR_CLIENT_ID";
export const GET_CALENDAR = "GET_CALENDAR";
export const TOKEN = "TOKEN";
export const GET_PAY_METHODS = "GET_PAY_METHODS"

//ACTIONSTYPES DE INVENTARIO

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
//CREACION DE INVENTARIO
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
//EDICION DE INVENTARIO
export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";
//EDICION DE PRECIO
export const GET_PRODUCT_PRICES_HISTORY_REQUEST =
  "GET_PRODUCT_PRICES_HISTORY_REQUEST";
export const GET_PRODUCT_PRICES_HISTORY_SUCCESS =
  "GET_PRODUCT_PRICES_HISTORY_SUCCESS";
export const GET_PRODUCT_PRICES_HISTORY_FAILURE =
  "GET_PRODUCT_PRICES_HISTORY_FAILURE";

export const UPDATE_PRODUCT_PRICE_REQUEST = "UPDATE_PRODUCT_PRICE_REQUEST";
export const UPDATE_PRODUCT_PRICE_SUCCESS = "UPDATE_PRODUCT_PRICE_SUCCESS";
export const UPDATE_PRODUCT_PRICE_FAILURE = "UPDATE_PRODUCT_PRICE_FAILURE";
